# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.15.9

# Mod Properties
mod_id=daycount
mod_name=DayCount
mod_version=1.3.9-mc1.20
maven_group=net.petemc.daycount
archives_base_name=DayCount

# Dependencies
fabric_version=0.92.2+1.20.1

modmenu_version=7.0.1
cloth_config_version=8.3.134
jade_version=5771000